package com.deltek.integration.maconomy.custom;

import static com.deltek.integration.maconomy.relations.LinkRelations.dataAnyKey;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;

import com.deltek.integration.maconomy.client.MaconomyClient;
import com.deltek.integration.maconomy.containers.v1.CardTableData;
import com.deltek.integration.maconomy.containers.v1.CardTableRecord;
import com.deltek.integration.maconomy.containers.v1.FilterData;
import com.deltek.integration.maconomy.containers.v1.FilterRecord;

/**
 * AUTO-GENERATED IMPLEMENTATION OF THE "NOTES" CONTAINER.
 * DO NOT EDIT THIS FILE BY HAND!
 */
public class Notes extends BaseContainer implements IHasFilter<Notes.Filter>, IHasCard<Notes.Card> {

	public Notes(final MaconomyClient client) {
		super(client, "Notes");
	}

	@Override
    public Function<FilterData, Notes.Filter> getFilterCtorFn() {
        return data -> new Notes.Filter(data);
    }

	@Override
    public Function<CardTableData, Notes.Card> getCardCtorFn() {
        return data -> new Notes.Card(data);
    }

	public static class Filter implements IFilter<Notes.Filter.InitRecord, Notes.Filter.Record>  {

		private final FilterData data;

		private Filter(final FilterData data) {
			this.data = data;
		}

		@Override
		public List<Notes.Filter.Record> records() {
			final List<Notes.Filter.Record> records = new ArrayList<>();
			for(final FilterRecord record : data.getPanes().getFilter().getRecords()) {
				records.add(new Notes.Filter.Record(record));
			}
			return records;
		}

		public static class InitRecord {
		}

		public static class Record {

			private final FilterRecord record;

			private Record(final FilterRecord record) {
				this.record = record;
			}

			public RStringField noteNumber() {
				return new RStringField(record.getData(), "notenumber");
			}

		}

	}

	@Override
	public Notes.Card card() {
		final CardTableData cardTableData = getClient().transition(getContainer(), dataAnyKey());
		return new Notes.Card(cardTableData);
	}

	public static class Card extends BaseCardPane<Notes.Card.InitRecord, Notes.Card.Record>  {

		private Card(final CardTableData cardTableData) {
			super(cardTableData,
				  record -> new Notes.Card.InitRecord(record),
				  record -> new Notes.Card.Record(record));
		}

		public static class InitRecord {

			private final CardTableRecord record;

			private InitRecord(final CardTableRecord cardTableRecord) {
				this.record = cardTableRecord;
			}

		}

		public static class Record {

			private final CardTableRecord record;

			private Record(final CardTableRecord cardTableRecord) {
				this.record = cardTableRecord;
			}

			public RWStringField noteNumber() {
				return new RWStringField(this.record.getData(), "notenumber");
			}

		}

	}

}
